const String STARTING_STATUS = "STARTING";
const String WAITING_FOR_WIFI_CONNECTION_STATUS = "WAITING_FOR_WIFI_CONNECTION";
const String CONNECTION_FAILED_STATUS = "CONNECTION_FAILED_STATUS";
const String CONNECTING_STATUS = "CONNECTING";
const String WIFI_CONNECTED_STATUS = "WIFI_CONNECTED";
